### ISSUE TITLE
println doesn't follow textsize

### ISSUE THREAD

**Issue by slavkoja** [dancol90/LightPCD8544#1]
Hi, firstly - great job, i cloned the repo, connectec cheap ebay's SSD1306 module and it works without any tweaks.

However, my eyes are too old for the default font size, then i set `setTextSize(2)`. The text is greater (and readable for me), but with the `println()` are lines overlaped. Please, can you implement it to respect text size?

regards

**Comment by dancol90** [comment]
Hi! Thanks for using my lib! 
Try now, it should work!

**Comment by slavkoja** [comment]
Thanks for quick response ;-)

The lines are now OK, but the chars has too big space between them now. IMO there is small mistake in your update:

```
cursor_x += text_prop.size * c_width;
```

It must be:

```
cursor_x += c_width;
```

because it seems, that the `drawChar()` returns width with text size calculated in its return value:

```
return (len * size) + 1;
```

But IMO here must be calculated the size for space (between chars) too:

```
return (len * size) + size;
```

(i am sorry, i am not familiar with pull requests)

**Comment by dancol90** [comment]
Yeah, you're right. Some time ago I've replaced all sizes references with a 1 (don't remember why, actually), and then I restored only some of them. Thanks for spotting the error!

**Comment by slavkoja** [comment]
Thanks, I will test it tomorrow (here is níght), but i have a plan to do some comparison vith Adafruit's libraries, mostly for Flash sizes and initial SRAM usage (as reported by Arduino for Leonardo board) to i can see, if it is really light ;-) Of course with the same code, e.g. draw circle, draw rectangle, etc.

Then i want to ask, if you are interested in publishing the results here on some as Wiki page or so... Beside the memory sizes, i will have some demo code, which i can provide too.

**Comment by dancol90** [comment]
Yeah, actually by "light" I mean feature-wise light, just the basic stuff for drawing and printing, to spare some flash memory on Arduino. It's inspired by adafruit's library, but I rewrote from scratch a lot of the code, so maybe some parts have better performance too!!

Every contribution is well accepted (I wouldn't published here on github otherwise!), so feel free to make some pull request for everything you want!

**Comment by slavkoja** [comment]
Dear, great job! I tested it and it works now as expected ;-)

Ad testing: OK, i will do some measurement now, but i am not interested in performance yet. I asked, because not all publishing here are willing to add all things. As i mentioned before, i am not familiar with pull requests yet, but after i will done (i hope today), i will create new issue for it, then IMO this one can be closed.

thanks for fixing
